services:
    sonata.admin.post:
        class: Ads\AdminBundle\Admin\PostAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Content", label: "Post" }
        arguments:
            - ~
            - Ads\AdminBundle\Entity\Post
            - ~
        calls:
            - [ setTranslationDomain, [AdsAdminBundle]]
